class CreateTableConfidenceHelper < ActiveRecord::Migration[5.1]
  def change
    execute("CREATE TABLE public.confidence_helper
    (
    confidence_no double precision,
                         user_count integer
    );")


    execute( " insert into confidence_helper (confidence_no, user_count) select 0 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.01 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.02 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.03 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.04 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.05 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.07 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.08 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.06 as confidence_no, 0 as user_count  ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.09 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.1 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.11 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.12 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.13 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.14 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.15 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.16 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.17 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.18 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.19 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.2 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.21 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.22 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.23 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.24 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.25 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.26 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.27 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.28 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.29 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.3 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.31 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.32 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.33 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.34 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.35 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.36 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.37 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.38 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.39 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.4 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.41 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.42 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.43 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.44 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.45 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.46 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.47 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.48 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.49 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.5 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.51 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.52 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.53 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.54 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.55 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.56 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.57 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.58 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.59 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.6 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.61 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.62 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.63 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.64 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.65 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.66 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.67 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.68 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.69 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.7 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.71 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.72 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.73 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.74 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.75 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.76 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.77 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.78 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.79 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.8 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.81 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.82 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.83 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.84 as confidence_no, 0 as user_count ;")  
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.85 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.86 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.87 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.88 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.89 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.9 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.91 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.92 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.93 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.94 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.95 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.96 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.97 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.98 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 0.99 as confidence_no, 0 as user_count ;")
    execute( " insert into confidence_helper (confidence_no, user_count) select 1 as confidence_no, 0 as user_count ;")

  end
end
